Parameters:
  LatestAmiId:
    Description: (DO NOT CHANGE)
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
    AllowedValues:
      - /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:
  MySSMRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ ec2.amazonaws.com ]
            Action: 
              - sts:AssumeRole
      Path: /

  MyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: [ !Ref MySSMRole ]

  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
     EnableDnsHostnames: true
     EnableDnsSupport: true
     CidrBlock: 10.0.0.0/16
     Tags:
        - Key: Name
          Value: My-VPC

  MyIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: My-IGW

  MyIGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref MyIGW
      VpcId: !Ref MyVPC

  MyPublicRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: My-Public-RT

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: MyIGWAttachment
    Properties:
      RouteTableId: !Ref MyPublicRT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyIGW

  MyPublicSN:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: Name
          Value: My-Public-SN

  MyPublicSN2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: My-Public-SN-2

  MyPublicSNRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref MyPublicRT
      SubnetId: !Ref MyPublicSN

  MyPublicSNRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref MyPublicRT
      SubnetId: !Ref MyPublicSN2

  ALBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB Security Group
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: ALB-SG
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

  KeyCloakSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: KeyCloak Security Group
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: KeyCloak-SG
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: !GetAtt MyVPC.CidrBlock

  LocustSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Locust Security Group
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: Locust-SG
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 8089
        ToPort: 8089
        CidrIp: 0.0.0.0/0

  WebSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: WEB Security Group
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: Web-SG
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        SourceSecurityGroupId: !Ref ALBSG

  MySSMEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      VpcId: !Ref MyVPC
      SubnetIds: 
        - !Ref MyPublicSN
        - !Ref MyPublicSN2
      SecurityGroupIds:
        - !Ref KeyCloakSG

  MySSMMSGEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssmmessages
      VpcId: !Ref MyVPC
      SubnetIds: 
        - !Ref MyPublicSN
        - !Ref MyPublicSN2
      SecurityGroupIds:
        - !Ref KeyCloakSG

  MyEC2MSGEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2messages
      VpcId: !Ref MyVPC
      SubnetIds: 
        - !Ref MyPublicSN
        - !Ref MyPublicSN2
      SecurityGroupIds:
        - !Ref KeyCloakSG

  KeyCloackServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref LatestAmiId
      IamInstanceProfile: !Ref MyInstanceProfile
      Tags:
        - Key: Name
          Value: KeyCloack-Server
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref MyPublicSN
          GroupSet:
          - !Ref KeyCloakSG
          AssociatePublicIpAddress: true
          PrivateIpAddress: 10.0.0.5
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            yum update -y
            yum install -y java-17-amazon-corretto-devel
            wget https://github.com/keycloak/keycloak/releases/download/22.0.5/keycloak-22.0.5.tar.gz
            tar xvfz keycloak-22.0.5.tar.gz
            mv keycloak-22.0.5 /usr/share/keycloack
            cd /usr/share/keycloack
            export KEYCLOAK_ADMIN=admin
            export KEYCLOAK_ADMIN_PASSWORD=123
            ./bin/kc.sh start-dev
            
  LocustServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref LatestAmiId
      Tags:
        - Key: Name
          Value: Locust-Server
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref MyPublicSN2
          GroupSet:
          - !Ref LocustSG
          AssociatePublicIpAddress: true
          PrivateIpAddress: 10.0.1.5
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            pip3 uninstall urllib3
            pip3 install urllib3==1.26.6 locust
            wget https://raw.githubusercontent.com/eljoelee/DevOps-Study/main/AWS/System%20Architecture/locustfile.py 
            locust

  WebServerOne:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref LatestAmiId
      Tags:
        - Key: Name
          Value: Web-Server-One
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref MyPublicSN
          GroupSet:
          - !Ref WebSG
          AssociatePublicIpAddress: true
          PrivateIpAddress: 10.0.0.10
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            yum update -y
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd.service
            touch index.html
            echo "<!DOCTYPE html><html><body><h1>Hello, I'm Server-one</h1></body></html>" > index.html
            mv index.html /var/www/html/
            systemctl restart httpd.service

  WebServerTwo:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref LatestAmiId
      Tags:
        - Key: Name
          Value: Web-Server-Two
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref MyPublicSN2
          GroupSet:
          - !Ref WebSG
          AssociatePublicIpAddress: true
          PrivateIpAddress: 10.0.1.10
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            yum update -y
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd.service
            touch index.html
            echo "<!DOCTYPE html><html><body><h1>Hello, I'm Server-two</h1></body></html>" > index.html
            mv index.html /var/www/html/
            systemctl restart httpd.service

  WebTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: WebTG
      Port: 80
      Protocol: HTTP
      HealthCheckPath: '/'
      VpcId: !Ref MyVPC
      Targets:
        - Id: !Ref WebServerOne
          Port: 80
        - Id: !Ref WebServerTwo
          Port: 80

  MyALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    DependsOn: MyIGWAttachment
    Properties:
      Scheme: internet-facing
      Name: My-ALB
      SecurityGroups:
        - !Ref ALBSG
      Subnets:
        - !Ref MyPublicSN
        - !Ref MyPublicSN2

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WebTG
      LoadBalancerArn: !Ref MyALB
      Port: 80
      Protocol: HTTP